NetworkHostTracker/Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model;
using NetworkHostTracker.Models;

namespace NetworkHostTracker.Controllers
{
    public class ApplicationsController : Controller
    {
        private NetHostTrackerContext db = new NetHostTrackerContext();

        // GET: Applications
        public async Task<ActionResult> Index()
        {
            return View(await db.Applications.ToListAsync());
        }

        // GET: Applications/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = await db.Applications.FindAsync(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }

        // GET: Applications/Create
        public ActionResult Create()
        {
            ViewBag.PrimaryHost = new SelectList(db.Hosts, "Id", "Name");
            return View();
        }

        // POST: Applications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Description,PrimaryHost")] Application application)
        {
            ViewBag.PrimaryHost = new SelectList(db.Hosts, "Id", "Name", application.PrimaryHost);
            if (ModelState.IsValid)
            {
                var testApplication = db.Applications.FirstOrDefault(e => e.Name == application.Name);
                if (testApplication == null)
                {
                    db.Applications.Add(application);
                    await db.SaveChangesAsync();
                    application = db.Applications.FirstOrDefault(e => e.Name == application.Name);
                    var applicationAssignment = new ApplicationAssignment();
                    applicationAssignment.ApplicationId = application.Id;
                    applicationAssignment.DateAssigned = DateTime.Now.GetCondensedDateTime();
                    applicationAssignment.HostId = application.PrimaryHost;
                    db.ApplicationAssignments.Add(applicationAssignment);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", "An application with the same name already exists.");
                return View(application);

            }

            return View(application);
        }

        // GET: Applications/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = await db.Applications.FindAsync(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            var applicationHosts = new List<int>();
            db.ApplicationAssignments.Where(e => e.ApplicationId == id).ToList().ForEach(e => applicationHosts.Add(e.HostId));
            ViewBag.PrimaryHost = new SelectList(db.Hosts.Where(e => applicationHosts.Contains(e.Id)), "Id", "Name", application.PrimaryHost);
            return View(application);
        }

        // POST: Applications/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Description,PrimaryHost")] Application application)
        {
            var applicationHosts = new List<int>();
            db.ApplicationAssignments.Where(e => e.ApplicationId == application.Id).ToList().ForEach(e => applicationHosts.Add(e.HostId));
            ViewBag.PrimaryHost = new SelectList(db.Hosts.Where(e => applicationHosts.Contains(e.Id)), "Id", "Name", application.PrimaryHost);
            if (ModelState.IsValid)
            {
                var testApplication = db.Applications.FirstOrDefault(e => e.Name == application.Name && e.Id != application.Id);
                if (testApplication == null)
                {

                    db.Entry(application).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    return RedirectToAction("Details", new { id = application.Id });
                }
                ModelState.AddModelError("", "An application with the same name already exists.");
                return View(application);
            }
            return View(application);
        }

        // GET: Applications/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = await db.Applications.FindAsync(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }

        // POST: Applications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Application application = await db.Applications.FindAsync(id);
            db.Applications.Remove(application);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NetworkHostTracker/Controllers/HostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model;
using NetworkHostTracker.Models;

namespace NetworkHostTracker.Controllers
{
    public class HostsController : Controller
    {
        private NetHostTrackerContext db = new NetHostTrackerContext();

        // GET: Hosts
        public async Task<ActionResult> Index()
        {
            return View(await db.Hosts.ToListAsync());
        }

        // GET: Hosts/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Host host = await db.Hosts.FindAsync(id);
            if (host == null)
            {
                return HttpNotFound();
            }
            return View(host);
        }

        // GET: Hosts/Create
        public ActionResult Create()
        {
            ViewBag.DefaultNetwork = new SelectList(db.Networks, "Id", "Name");
            ViewBag.LocationId = new SelectList(db.Locations, "Id", "Name");
            ViewBag.HostTypeId = new SelectList(db.HostTypes, "Id", "Name");
            ViewBag.PhysicalHostId = new SelectList(db.Hosts.Where(e => e.IsPhysical == true), "Id", "Name");

            return View();
        }

        // POST: Hosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Description,DomainName,IpAddress,DefaultNetwork,DefaultNetworkIpAddress,HostTypeId,Make,LocationId,IsPhysical,PhyisicalHostId")] Host host)
        {
            ViewBag.DefaultNetwork = new SelectList(db.Networks, "Id", "Name", host.DefaultNetwork);
            ViewBag.LocationId = new SelectList(db.Locations, "Id", "Name", host.LocationId);
            ViewBag.HostTypeId = new SelectList(db.HostTypes, "Id", "Name", host.HostTypeId);
            ViewBag.PhysicalHostId = new SelectList(db.Hosts.Where(e => e.IsPhysical == true), "Id", "Name", host.PhysicalHostId);

            if (ModelState.IsValid)
            {
                if (string.IsNullOrEmpty(host.DefaultNetworkIpAddress))
                {
                    ModelState.AddModelError("", "Please specify the IP address of the host in the default network.");
                    return View(host);
                }
                var testHost = db.Locations.FirstOrDefault(e => e.Name == host.Name);
                if (testHost == null)
                {
                    var testHost2 = db.Locations.FirstOrDefault(e => e.Name == host.DomainName);
                    if (testHost2 == null)
                    {
                        db.Hosts.Add(host);
                        //Check if IP address belongs to this subnet
                        var network = await db.Networks.FindAsync(host.DefaultNetwork);
                        try
                        {
                            if (BusinessLogic.BusinessLogic.IsIpAddressInNetwork(network, host.DefaultNetworkIpAddress))
                            {
                                //Check if IP address is free
                                var testAssignment = db.HostAssignments.FirstOrDefault(e => e.NetworkId == network.Id && e.IpAddress == host.DefaultNetworkIpAddress);
                                if (testAssignment == null)
                                {
                                    var hostAssignment = new HostAssignment();
                                    hostAssignment.HostId = host.Id;
                                    hostAssignment.NetworkId = host.DefaultNetwork;
                                    hostAssignment.IpAddress = host.DefaultNetworkIpAddress;
                                    hostAssignment.DateAssigned = DateTime.Now.GetCondensedDateTime();
                                    db.HostAssignments.Add(hostAssignment);
                                    await db.SaveChangesAsync();
                                    return RedirectToAction("Index");
                                }
                                ModelState.AddModelError("", "The IP address you entered has already been assigned to another host.");
                                return View(host);
                            }
                            ModelState.AddModelError("", "The IP address you entered does not belong to the network you selected.");
                            return View(host);
                        }
                        catch (Exception e)
                        {
                            ModelState.AddModelError("", e.Message);
                            return View(host);
                        }
                    }
                    ModelState.AddModelError("", "A host with the same domain name already exists.");
                    return View(host);
                }
                ModelState.AddModelError("", "A host with the same name already exists.");
                return View(host);
            }
            return View(host);
        }

        // GET: Hosts/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Host host = await db.Hosts.FindAsync(id);
            if (host == null)
            {
                return HttpNotFound();
            }
            var hostNetworks = new List<int>();
            db.HostAssignments.Where(e => e.HostId == id).ToList().ForEach(e => hostNetworks.Add(e.NetworkId));
            ViewBag.DefaultNetwork = new SelectList(db.Networks.Where(e => hostNetworks.Contains(e.Id)), "Id", "Name", host.DefaultNetwork);
            ViewBag.LocationId = new SelectList(db.Locations, "Id", "Name", host.LocationId);
            ViewBag.HostTypeId = new SelectList(db.HostTypes, "Id", "Name", host.HostTypeId);
            ViewBag.PhysicalHostId = new SelectList(db.Hosts.Where(e => e.IsPhysical == true), "Id", "Name", host.PhysicalHostId);

            return View(host);
        }

        // POST: Hosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Description,DomainName,IpAddress,DefaultNetwork,DefaultNetworkIpAddress,HostTypeId,Make,LocationId,IsPhysical,PhysicalHostId")] Host host)
        {
            var hostNetworks = new List<int>();
            db.HostAssignments.Where(e => e.HostId == host.Id).ToList().ForEach(e => hostNetworks.Add(e.NetworkId));
            ViewBag.DefaultNetwork = new SelectList(db.Networks.Where(e => hostNetworks.Contains(e.Id)), "Id", "Name", host.DefaultNetwork);
            ViewBag.LocationId = new SelectList(db.Locations, "Id", "Name", host.LocationId);
            ViewBag.HostTypeId = new SelectList(db.HostTypes, "Id", "Name", host.HostTypeId);
            ViewBag.PhysicalHostId = new SelectList(db.Hosts.Where(e => e.IsPhysical == true), "Id", "Name", host.PhysicalHostId);

            if (ModelState.IsValid)
            {
                var testHost = db.Locations.FirstOrDefault(e => e.Name == host.Name && e.Id != host.Id);
                if (testHost == null)
                {
                    var testHost2 = db.Locations.FirstOrDefault(e => e.Name == host.DomainName && e.Id != host.Id);
                    if (testHost2 == null)
                    {
                        var hostAssignment = db.HostAssignments.Find(host.DefaultNetwork, host.Id, host.DefaultNetworkIpAddress);
                        host.DefaultNetworkIpAddress = hostAssignment.IpAddress;
                        db.Entry(host).State = EntityState.Modified;
                        await db.SaveChangesAsync();
                        return RedirectToAction("Details", new { id = host.Id });
                    }
                    ModelState.AddModelError("", "A host with the same domain name already exists.");
                }
                ModelState.AddModelError("", "A host with the same name already exists.");
            }
            return View(host);
        }

        // GET: Hosts/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Host host = await db.Hosts.FindAsync(id);
            if (host == null)
            {
                return HttpNotFound();
            }
            return View(host);
        }

        // POST: Hosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Host host = await db.Hosts.FindAsync(id);
            var applicationHostAssignments = db.ApplicationAssignments.Where(e => e.HostId == host.Id).ToList();
            if (applicationHostAssignments.Count() > 0)
            {
                ModelState.AddModelError("", $"This operation cannot be completed because the host has {applicationHostAssignments.Count()} application/s associated with it.");
                return View(host);
            }
            var applicationsWithAsDefault = db.Applications.Where(e => e.PrimaryHost == host.Id).ToList();
            if (applicationsWithAsDefault.Count() > 0)
            {

NetworkHostTracker/Views/ApplicationAssignments/Create.cshtml
@model Model.ApplicationAssignment

@{
    ViewBag.Title = "New Application Assignment";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h5 class="text-secondary">@ViewBag.Title</h5>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.ApplicationId, "ApplicationId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ApplicationId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ApplicationId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HostId, "HostId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("HostId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.HostId, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.DateAssigned, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateAssigned, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateAssigned, "", new { @class = "text-danger" })
            </div>
        </div>*@
    <br />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-success" />
            <button class="btn btn-info">@Html.ActionLink("Cancel", "Index", null, new { style = "decoration: none", @class = "text-light" })</button>
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NetworkHostTracker/Views/ApplicationAssignments/Delete.cshtml
@model Model.ApplicationAssignment

@{
    ViewBag.Title = "Delete";
}

<h5 class="text-secondary">Are you sure you want to revoke the assignment of the @Model.Application.Name application to @Model.Host.Name?</h5>
<div>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <br />
    <table class="display table table-striped table-bordered shadow" style="width:100%" width="100%" cellspacing="0">
        <thead>
            <tr class="bg-info">
                <th>
                    @*@Html.DisplayNameFor(model => model.Host.Name)*@ Application
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.Network.Name)*@ Host
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DateAssigned)
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Html.ActionLink(Model.Application.Name, "Details", "Applications", new { id = Model.ApplicationId }, null)
                </td>
                <td>
                    @Html.ActionLink(Model.Host.Name, "Details", "Hosts", new { id = Model.HostId }, null)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.DateAssigned)
                </td>
            </tr>
    </table>
    <br />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-danger" />
        <button class="btn btn-info">@Html.ActionLink("Cancel", "Index", null, new { style = "decoration: none", @class = "text-light" })</button>
    </div>
    }
</div>

NetworkHostTracker/Views/ApplicationAssignments/Details.cshtml
@model Model.ApplicationAssignment

@{
    ViewBag.Title = "Details";
}

<h5>@ViewBag.Title </h5>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Application.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Application.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Host.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Host.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateAssigned)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateAssigned)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NetworkHostTracker/Views/ApplicationAssignments/Edit.cshtml
@model Model.ApplicationAssignment

@{
    ViewBag.Title = "Edit";
}

<h5>@ViewBag.Title </h5>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Application Assignment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ApplicationId)

        @Html.HiddenFor(model => model.HostId)

        <div class="form-group">
            @Html.LabelFor(model => model.DateAssigned, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateAssigned, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateAssigned, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NetworkHostTracker/Views/ApplicationAssignments/Index.cshtml
@model IEnumerable<Model.ApplicationAssignment>

@{
    ViewBag.Title = "Application Assignments";
}

<div class="card shadow">
    <div class="card-header bg-info">
        <h5 class="text-light">@ViewBag.Title</h5>
    </div>
    <div class="card-body">
        <p>
            @Html.ActionLink("  ", "Create", null, new { @class = "fa fa-plus-square" })
        </p>
        <hr />
        <table class="display table table-striped table-bordered" id="report" style="width:100%" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>
                        @*@Html.DisplayNameFor(model => model.Application.Name)*@ Application
                    </th>
                    <th>
                        @*@Html.DisplayNameFor(model => model.Host.Name)*@ Host
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DateAssigned)
                    </th>
                    <th></th>
                </tr>
                </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.ActionLink(item.Application.Name, "Details", "Applications", new { id = item.ApplicationId }, null)
                        </td>
                        <td>
                            @Html.ActionLink(item.Host.Name, "Details", "Hosts", new { id = item.HostId }, null)

                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DateAssigned)
                        </td>
                        <td>
                            @*@Html.ActionLink(" ", "Edit", new { applicationId = item.ApplicationId, hostId = item.HostId }, new { @class = "fa fa-edit" }) |
                            @Html.ActionLink(" ", "Details", new { applicationId = item.ApplicationId, hostId = item.HostId }, new { @class = "fa fa-search-plus" }) |*@
                            @Html.ActionLink(" ", "Delete", new { applicationId = item.ApplicationId, hostId = item.HostId }, new { @class = "fa fa-trash" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
</div>
</div>