NetworkHostTracker/Controllers/HostAssignmentsController.cs
using Model;
using NetworkHostTracker.Models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace NetworkHostTracker.Controllers
{
    public class HostAssignmentsController : Controller
    {
        private NetHostTrackerContext db = new NetHostTrackerContext();

        // GET: HostAssignments
        public async Task<ActionResult> Index()
        {
            var hostAssignments = db.HostAssignments.Include(h => h.Host).Include(h => h.Network);
            return View(await hostAssignments.ToListAsync());
        }

        // GET: HostAssignments/Details/5
        public async Task<ActionResult> Details(int? hostId, int? networkId, string ipAddress)
        {
            if (hostId == null || networkId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HostAssignment hostAssignment = await db.HostAssignments.FindAsync(networkId, hostId, ipAddress);
            if (hostAssignment == null)
            {
                return HttpNotFound();
            }
            return View(hostAssignment);
        }

        // GET: HostAssignments/Create
        public ActionResult Create()
        {
            ViewBag.HostId = new SelectList(db.Hosts, "Id", "Name");
            ViewBag.NetworkId = new SelectList(db.Networks, "Id", "Name");
            return View();
        }

        // POST: HostAssignments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "NetworkId,HostId,IpAddress")] HostAssignment hostAssignment)
        {
            ViewBag.HostId = new SelectList(db.Hosts, "Id", "Name", hostAssignment.HostId);
            ViewBag.NetworkId = new SelectList(db.Networks, "Id", "Name", hostAssignment.NetworkId);
            if (ModelState.IsValid)
            {
                if (!BusinessLogic.BusinessLogic.IsIpAddressValid(hostAssignment.IpAddress))
                {
                    ModelState.AddModelError("", "The IP address you entered is invalid.");
                    return View(hostAssignment);
                }
                //Check if this assignment does not already exist i.e. the combination of host, network and IP address
                var host = await db.Hosts.FindAsync(hostAssignment.HostId);
                var network = await db.Networks.FindAsync(hostAssignment.NetworkId);
                var oldHostAssignment = await db.HostAssignments.FindAsync(hostAssignment.NetworkId, hostAssignment.HostId, hostAssignment.IpAddress);
                if (oldHostAssignment == null)
                {
                    //Check if IP address belongs to this subnet
                    if (BusinessLogic.BusinessLogic.IsIpAddressInNetwork(network, hostAssignment.IpAddress))
                    {
                        //Check if IP address is free
                        var testAssignment = db.HostAssignments.FirstOrDefault(e => e.NetworkId == hostAssignment.NetworkId && e.IpAddress == hostAssignment.IpAddress);
                        if (testAssignment == null)
                        {
                            hostAssignment.DateAssigned = DateTime.Now.GetCondensedDateTime();
                            db.HostAssignments.Add(hostAssignment);
                            await db.SaveChangesAsync();
                            return RedirectToAction("Index");
                        }
                        ModelState.AddModelError("", "The IP address you entered has already been assigned to another host.");
                        return View(hostAssignment);
                    }
                    ModelState.AddModelError("", "The IP address you entered does not belong to the network you selected.");
                    return View(hostAssignment);
                }
                ModelState.AddModelError("", "This host already belongs to this network with the specified IP address.");
                return View(hostAssignment);
            }
            return View(hostAssignment);
        }

        // GET: HostAssignments/Edit/5
        public async Task<ActionResult> Edit(int? hostId, int? networkId, string ipAddress)
        {
            if (hostId == null || networkId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HostAssignment hostAssignment = await db.HostAssignments.FindAsync(networkId, hostId, ipAddress);
            if (hostAssignment == null)
            {
                return HttpNotFound();
            }
            ViewBag.HostId = new SelectList(db.Hosts, "Id", "Name", hostAssignment.HostId);
            ViewBag.NetworkId = new SelectList(db.Networks, "Id", "Name", hostAssignment.NetworkId);
            return View(hostAssignment);
        }

        // POST: HostAssignments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "NetworkId,HostId,IpAddress,DateAssigned")] HostAssignment hostAssignment)
        {
            ViewBag.HostId = new SelectList(db.Hosts, "Id", "Name", hostAssignment.HostId);
            ViewBag.NetworkId = new SelectList(db.Networks, "Id", "Name", hostAssignment.NetworkId);
            if (ModelState.IsValid)
            {
                if (!BusinessLogic.BusinessLogic.IsIpAddressValid(hostAssignment.IpAddress))
                {
                    ModelState.AddModelError("", "The IP address you entered is invalid.");
                    return View(hostAssignment);
                }
                var host = await db.Hosts.FindAsync(hostAssignment.HostId);
                var network = await db.Networks.FindAsync(hostAssignment.NetworkId);
                var oldHostAssignment = await db.HostAssignments.FindAsync(hostAssignment.NetworkId, hostAssignment.HostId, hostAssignment.IpAddress);
                if (oldHostAssignment == null)
                {
                    //Check if IP address belongs to this subnet
                    if (BusinessLogic.BusinessLogic.IsIpAddressInNetwork(network, hostAssignment.IpAddress))
                    {
                        //Check if IP address is free
                        var testAssignment = db.HostAssignments.FirstOrDefault(e => e.NetworkId == hostAssignment.NetworkId && e.IpAddress == hostAssignment.IpAddress);
                        if (testAssignment == null)
                        {
                            var tempAssignment = db.HostAssignments.FirstOrDefault(e => e.NetworkId == hostAssignment.NetworkId && e.HostId == hostAssignment.HostId && e.DateAssigned == hostAssignment.DateAssigned);
                            //tempAssignment = await db.HostAssignments.FindAsync(hostAssignment.NetworkId, hostAssignment.HostId, tempAssignment.IpAddress);
                            //tempAssignment.IpAddress = hostAssignment.IpAddress;
                            //tempAssignment.DateAssigned = DateTime.Now.GetCondensedDateTime();
                            hostAssignment.DateAssigned = DateTime.Now.GetCondensedDateTime();
                            db.Entry(tempAssignment).State = EntityState.Deleted;
                            db.Entry(hostAssignment).State = EntityState.Added;
                            if (host.DefaultNetwork == hostAssignment.NetworkId)
                            {
                                host.DefaultNetworkIpAddress = hostAssignment.IpAddress;
                                db.Entry(host).State = EntityState.Modified;
                            }
                            await db.SaveChangesAsync();
                            return RedirectToAction("Index");
                        }
                        ModelState.AddModelError("", "The IP address you entered has already been assigned to another host.");
                        return View(hostAssignment);
                    }
                    ModelState.AddModelError("", "The IP address you entered does not belong to the network you selected.");
                    return View(hostAssignment);
                }
                ModelState.AddModelError("", "This host already belongs to this network with the specified IP address.");
                return View(hostAssignment);
        }
            return View(hostAssignment);
        }

        // GET: HostAssignments/Delete/5
        public async Task<ActionResult> Delete(int? hostId, int? networkId, string ipAddress)
        {
            if (hostId == null || networkId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HostAssignment hostAssignment = await db.HostAssignments.FindAsync(networkId, hostId, ipAddress);
            if (hostAssignment == null)
            {
                return HttpNotFound();
            }
            return View(hostAssignment);
        }

        // POST: HostAssignments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int hostId, int networkId, string ipAddress)
        {
            HostAssignment hostAssignment = await db.HostAssignments.FindAsync(networkId, hostId, ipAddress);
            var host = await db.Hosts.FindAsync(hostId);
            if(host.DefaultNetwork == networkId)
            {
                ModelState.AddModelError("", "This association defines the host's default network. Please assign a new default network for the host first.");

NetworkHostTracker/Controllers/HostTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model;

namespace NetworkHostTracker.Controllers
{
    public class HostTypesController : Controller
    {
        private NetHostTrackerContext db = new NetHostTrackerContext();

        // GET: HostTypes
        public async Task<ActionResult> Index()
        {
            return View(await db.HostTypes.ToListAsync());
        }

        // GET: HostTypes/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HostType hostType = await db.HostTypes.FindAsync(id);
            if (hostType == null)
            {
                return HttpNotFound();
            }
            return View(hostType);
        }

        // GET: HostTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HostTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Description")] HostType hostType)
        {
            if (ModelState.IsValid)
            {
                var testHostType = db.Locations.FirstOrDefault(e => e.Name == hostType.Name);
                if (testHostType == null)
                {
                    db.HostTypes.Add(hostType);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", "A host type with the same name already exists.");
            }

            return View(hostType);
        }

        // GET: HostTypes/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HostType hostType = await db.HostTypes.FindAsync(id);
            if (hostType == null)
            {
                return HttpNotFound();
            }
            return View(hostType);
        }

        // POST: HostTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name")] HostType hostType)
        {
            if (ModelState.IsValid)
            {
                var testHostType = db.Locations.FirstOrDefault(e => e.Name == hostType.Name && e.Id != hostType.Id);
                if (testHostType == null)
                {
                    db.Entry(hostType).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    return RedirectToAction("Details", new { id = hostType.Id });
                }
                ModelState.AddModelError("", "A host type with the same name already exists.");
            }
            return View(hostType);
        }

        // GET: HostTypes/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HostType hostType = await db.HostTypes.FindAsync(id);
            if (hostType == null)
            {
                return HttpNotFound();
            }
            return View(hostType);
        }

        // POST: HostTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            HostType hostType = await db.HostTypes.FindAsync(id);
            if (hostType.Hosts.Count() > 0)
            {
                ModelState.AddModelError("", "This operation cannot be completed because the host type has hosts associated with it.");
                return View(hostType);
            }
            db.HostTypes.Remove(hostType);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NetworkHostTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Network Host Tracker</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-info">
        <div class="container">
            @*<div class="navbar-header">*@
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"></button>
            @Html.ActionLink("Network Host Tracker", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            @*</div>*@
            <div class="navbar-collapse collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item">@Html.ActionLink("Networks", "Index", "Networks", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Hosts", "Index", "Hosts", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Applications", "Index", "Applications", null, new { @class = "nav-link" })</li>
                    <li class="dropdown  nav-item">
                        <a class="dropdown-toggle nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Assignments</a>
                        <ul class="dropdown-menu bg-info" aria-labelledby="navbarDropdown">
                            <li class="nav-item">@Html.ActionLink("Host", "Index", "HostAssignments", null, new { @class = "nav-link" })</li>
                            <li class="nav-item">@Html.ActionLink("Application", "Index", "ApplicationAssignments", null, new { @class = "nav-link" })</li>
                        </ul>
                    </li>
                    <li class="dropdown  nav-item">
                        <a class="dropdown-toggle nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Other</a>
                        <ul class="dropdown-menu bg-info" aria-labelledby="navbarDropdown">
                            <li class="nav-item">@Html.ActionLink("Host Types", "Index", "HostTypes", null, new { @class = "nav-link" })</li>
                            <li class="nav-item">@Html.ActionLink("Locations", "Index", "Locations", null, new { @class = "nav-link" })</li>
                        </ul>
                    </li>
                </ul>
                <span class="nav navbar-text text-right">Hello, @User.Identity.Name</span>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        <br />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - James Taruvinga</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
        $(document).ready(function () {
            $('#report').DataTable({
                "dom": '<"top"lfi>rt<"bottom"p><"clear">',
            });
        });
        $(document).ready(function () {
            $('#report2').DataTable({
                "dom": '<"top"lfi>rt<"bottom"p><"clear">',
            });
        });

        $(document).ready(function () {
            $('#report3').DataTable({
                "dom": '<"top"lfi>rt<"bottom"p><"clear">',
            });
        });

    </script>
</body>
</html>