NetworkHostTracker/Controllers/HostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model;
using NetworkHostTracker.Models;

namespace NetworkHostTracker.Controllers
{
    public class HostsController : Controller
    {
        private NetHostTrackerContext db = new NetHostTrackerContext();

        // GET: Hosts
        public async Task<ActionResult> Index()
        {
            return View(await db.Hosts.ToListAsync());
        }

        // GET: Hosts/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Host host = await db.Hosts.FindAsync(id);
            if (host == null)
            {
                return HttpNotFound();
            }
            return View(host);
        }

        // GET: Hosts/Create
        public ActionResult Create()
        {
            ViewBag.DefaultNetwork = new SelectList(db.Networks, "Id", "Name");
            ViewBag.LocationId = new SelectList(db.Locations, "Id", "Name");
            ViewBag.HostTypeId = new SelectList(db.HostTypes, "Id", "Name");
            ViewBag.PhysicalHostId = new SelectList(db.Hosts.Where(e => e.IsPhysical == true), "Id", "Name");

            return View();
        }

        // POST: Hosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Description,DomainName,IpAddress,DefaultNetwork,DefaultNetworkIpAddress,HostTypeId,Make,LocationId,IsPhysical,PhyisicalHostId")] Host host)
        {
            ViewBag.DefaultNetwork = new SelectList(db.Networks, "Id", "Name", host.DefaultNetwork);
            ViewBag.LocationId = new SelectList(db.Locations, "Id", "Name", host.LocationId);
            ViewBag.HostTypeId = new SelectList(db.HostTypes, "Id", "Name", host.HostTypeId);
            ViewBag.PhysicalHostId = new SelectList(db.Hosts.Where(e => e.IsPhysical == true), "Id", "Name", host.PhysicalHostId);

            if (ModelState.IsValid)
            {
                if (string.IsNullOrEmpty(host.DefaultNetworkIpAddress))
                {
                    ModelState.AddModelError("", "Please specify the IP address of the host in the default network.");
                    return View(host);
                }
                var testHost = db.Locations.FirstOrDefault(e => e.Name == host.Name);
                if (testHost == null)
                {
                    var testHost2 = db.Locations.FirstOrDefault(e => e.Name == host.DomainName);
                    if (testHost2 == null)
                    {
                        db.Hosts.Add(host);
                        //Check if IP address belongs to this subnet
                        var network = await db.Networks.FindAsync(host.DefaultNetwork);
                        try
                        {
                            if (BusinessLogic.BusinessLogic.IsIpAddressInNetwork(network, host.DefaultNetworkIpAddress))
                            {
                                //Check if IP address is free
                                var testAssignment = db.HostAssignments.FirstOrDefault(e => e.NetworkId == network.Id && e.IpAddress == host.DefaultNetworkIpAddress);
                                if (testAssignment == null)
                                {
                                    var hostAssignment = new HostAssignment();
                                    hostAssignment.HostId = host.Id;
                                    hostAssignment.NetworkId = host.DefaultNetwork;
                                    hostAssignment.IpAddress = host.DefaultNetworkIpAddress;
                                    hostAssignment.DateAssigned = DateTime.Now.GetCondensedDateTime();
                                    db.HostAssignments.Add(hostAssignment);
                                    await db.SaveChangesAsync();
                                    return RedirectToAction("Index");
                                }
                                ModelState.AddModelError("", "The IP address you entered has already been assigned to another host.");
                                return View(host);
                            }
                            ModelState.AddModelError("", "The IP address you entered does not belong to the network you selected.");
                            return View(host);
                        }
                        catch (Exception e)
                        {
                            ModelState.AddModelError("", e.Message);
                            return View(host);
                        }
                    }
                    ModelState.AddModelError("", "A host with the same domain name already exists.");
                    return View(host);
                }
                ModelState.AddModelError("", "A host with the same name already exists.");
                return View(host);
            }
            return View(host);
        }

        // GET: Hosts/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Host host = await db.Hosts.FindAsync(id);
            if (host == null)
            {
                return HttpNotFound();
            }
            var hostNetworks = new List<int>();
            db.HostAssignments.Where(e => e.HostId == id).ToList().ForEach(e => hostNetworks.Add(e.NetworkId));
            ViewBag.DefaultNetwork = new SelectList(db.Networks.Where(e => hostNetworks.Contains(e.Id)), "Id", "Name", host.DefaultNetwork);
            ViewBag.LocationId = new SelectList(db.Locations, "Id", "Name", host.LocationId);
            ViewBag.HostTypeId = new SelectList(db.HostTypes, "Id", "Name", host.HostTypeId);
            ViewBag.PhysicalHostId = new SelectList(db.Hosts.Where(e => e.IsPhysical == true), "Id", "Name", host.PhysicalHostId);

            return View(host);
        }

        // POST: Hosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Description,DomainName,IpAddress,DefaultNetwork,DefaultNetworkIpAddress,HostTypeId,Make,LocationId,IsPhysical,PhysicalHostId")] Host host)
        {
            var hostNetworks = new List<int>();
            db.HostAssignments.Where(e => e.HostId == host.Id).ToList().ForEach(e => hostNetworks.Add(e.NetworkId));
            ViewBag.DefaultNetwork = new SelectList(db.Networks.Where(e => hostNetworks.Contains(e.Id)), "Id", "Name", host.DefaultNetwork);
            ViewBag.LocationId = new SelectList(db.Locations, "Id", "Name", host.LocationId);
            ViewBag.HostTypeId = new SelectList(db.HostTypes, "Id", "Name", host.HostTypeId);
            ViewBag.PhysicalHostId = new SelectList(db.Hosts.Where(e => e.IsPhysical == true), "Id", "Name", host.PhysicalHostId);

            if (ModelState.IsValid)
            {
                var testHost = db.Locations.FirstOrDefault(e => e.Name == host.Name && e.Id != host.Id);
                if (testHost == null)
                {
                    var testHost2 = db.Locations.FirstOrDefault(e => e.Name == host.DomainName && e.Id != host.Id);
                    if (testHost2 == null)
                    {
                        var hostAssignment = db.HostAssignments.Find(host.DefaultNetwork, host.Id, host.DefaultNetworkIpAddress);
                        host.DefaultNetworkIpAddress = hostAssignment.IpAddress;
                        db.Entry(host).State = EntityState.Modified;
                        await db.SaveChangesAsync();
                        return RedirectToAction("Details", new { id = host.Id });
                    }
                    ModelState.AddModelError("", "A host with the same domain name already exists.");
                }
                ModelState.AddModelError("", "A host with the same name already exists.");
            }
            return View(host);
        }

        // GET: Hosts/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Host host = await db.Hosts.FindAsync(id);
            if (host == null)
            {
                return HttpNotFound();
            }
            return View(host);
        }

        // POST: Hosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Host host = await db.Hosts.FindAsync(id);
            var applicationHostAssignments = db.ApplicationAssignments.Where(e => e.HostId == host.Id).ToList();
            if (applicationHostAssignments.Count() > 0)
            {
                ModelState.AddModelError("", $"This operation cannot be completed because the host has {applicationHostAssignments.Count()} application/s associated with it.");
                return View(host);
            }
            var applicationsWithAsDefault = db.Applications.Where(e => e.PrimaryHost == host.Id).ToList();
            if (applicationsWithAsDefault.Count() > 0)
            {

NetworkHostTracker/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model;

namespace NetworkHostTracker.Controllers
{
    public class LocationsController : Controller
    {
        private NetHostTrackerContext db = new NetHostTrackerContext();

        // GET: Locations
        public async Task<ActionResult> Index()
        {
            return View(await db.Locations.ToListAsync());
        }

        // GET: Locations/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = await db.Locations.FindAsync(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // GET: Locations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Locations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Description")] Location location)
        {
            if (ModelState.IsValid)
            {
                var testLocation = db.Locations.FirstOrDefault(e => e.Name == location.Name);
                if(testLocation == null)
                {
                    db.Locations.Add(location);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", "A location with the same name already exists.");
            }

            return View(location);
        }

        // GET: Locations/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = await db.Locations.FindAsync(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Locations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Description")] Location location)
        {
            if (ModelState.IsValid)
            {
                var testLocation = db.Locations.FirstOrDefault(e => e.Name == location.Name && e.Id != location.Id);
                if (testLocation == null)
                {
                    db.Entry(location).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    return RedirectToAction("Details", new { id = location.Id });
                }
                ModelState.AddModelError("", "A location with the same name already exists.");
            }
            return View(location);
        }

        // GET: Locations/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = await db.Locations.FindAsync(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Location location = await db.Locations.FindAsync(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            if (location.Hosts.Count() > 0)
            {
                ModelState.AddModelError("", "This operation cannot be complted because the location has hosts associated with it.");
                return View(location);
            }
            db.Locations.Remove(location);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NetworkHostTracker/Views/Locations/Create.cshtml
@model Model.Location

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Location</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NetworkHostTracker/Views/Locations/Delete.cshtml
@model Model.Location

@{
    ViewBag.Title = "Delete";
}

<h4 class="text-secondary">Are you sure you want to delete location '@Model.Name'?</h4>
<br />
<div>
    <p>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    </p>
    <table class="display table table-striped table-bordered shadow" style="width:100%" width="100%" cellspacing="0">
        <thead>
            <tr class="bg-info">
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                @*<th></th>*@
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Html.ActionLink(Model.Name, "Details", "Locations", new { id = Model.Id }, null)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.Description)
                </td>

                @*<td>
                    @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @class = "fa fa-edit" }) |
                    @Html.ActionLink(" ", "Details", new { id = item.Id }, new { @class = "fa fa-search-plus" }) |
                    @Html.ActionLink(" ", "Delete", new { id = item.Id }, new { @class = "fa fa-trash" })
                    </td>*@
            </tr>
        </tbody>
    </table>
    <br />
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
            <button class="btn btn-info">@Html.ActionLink("Cancel", "Details", new { id = Model.Id }, new { style = "decoration: none", @class = "text-light" })</button>
        </div>
    }
</div>

NetworkHostTracker/Views/Locations/Details.cshtml
@model Model.Location

@{
    ViewBag.Title = "Location Name";
    ViewBag.SubTitle = Model.Name;
}

<h5 class="text-secondary">@ViewBag.Title &raquo; @ViewBag.SubTitle</h5>
<div class="btn-group">
    <span class="btn btn-sm btn-outline-light">@Html.ActionLink(" ", "Index", null, new { @class = "text-info fa fa-arrow-left" }) </span>
    <span class="btn btn-sm btn-outline-light">@Html.ActionLink(" ", "Edit", new { id = Model.Id }, new { @class = "text-info fa fa-edit" })</span>
    <span class="btn btn-sm btn-outline-light">@Html.ActionLink(" ", "Delete", new { id = Model.Id }, new { @class = "text-info fa fa-trash" })</span>
</div>

<table class="table table-striped able-bordered table-responsive-md shadow">
    <tr class="bg-info">
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
    </tr>
    <tr>
        <td>
            @if (string.IsNullOrEmpty(Model.Description))
            {
                <i>None</i>
            }
            else
            {
                @Html.DisplayFor(modelItem => Model.Description)
            }
        </td>
    </tr>
</table>
<br />
<div>
    <div class="card shadow">
        <div class="card-header bg-info"><h5>Hosts</h5></div>
        <div class="card-body">
            <table class="display table table-striped table-bordered table-responsive-md table-hover" style="width:100%" id="report" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            Host
                        </th>
                        <th>
                            Description
                        </th>
                        <th>
                            Host IP Address
                        </th>
                        <th>
                            Host Type
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Hosts)
                    {
                        <tr>
                            <td>
                                @Html.ActionLink(item.Name, "Details", "Hosts", new { id = item.Id }, null)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>
                                @Html.ActionLink(item.DefaultNetworkIpAddress, "Details", "Hosts", new { id = item.Id }, null)
                            </td>
                            <td>
                                @Html.ActionLink(item.HostType.Name, "Details", "HostTypes", new { id = item.HostTypeId }, null)
                            </td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>
    </div>

</div>

NetworkHostTracker/Views/Locations/Edit.cshtml
@model Model.Location

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h5 class="text-secondary">Edit Location '@Model.Name'</h5>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-success" />
            <button class="btn btn-info">@Html.ActionLink("Cancel", "Details", new { id = Model.Id }, new { style = "decoration: none", @class = "text-light" })</button>
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NetworkHostTracker/Views/Locations/Index.cshtml
@model IEnumerable<Model.Location>

@{
    ViewBag.Title = "Locations";
}

<div class="card shadow">
    <div class="card-header bg-info">
        <h5 class="text-light">@ViewBag.Title</h5>
    </div>
    <div class="card-body">
        <p>
            @Html.ActionLink("  ", "Create", null, new { @class = "fa fa-plus-square" })
        </p>
        <hr />
        <table class="display table table-striped table-bordered" style="width:100%" id="report" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    @*<th></th>*@
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.ActionLink(item.Name, "Details", "Locations", new { id = item.Id }, null)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        @*<td>
                            @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @class = "fa fa-edit" }) |
                            @Html.ActionLink(" ", "Details", new { id = item.Id }, new { @class = "fa fa-search-plus" }) |
                            @Html.ActionLink(" ", "Delete", new { id = item.Id }, new { @class = "fa fa-trash" })
                        </td>*@
                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>