NetworkHostTracker/Controllers/HostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model;
using NetworkHostTracker.Models;

namespace NetworkHostTracker.Controllers
{
    public class HostsController : Controller
    {
        private NetHostTrackerContext db = new NetHostTrackerContext();

        // GET: Hosts
        public async Task<ActionResult> Index()
        {
            return View(await db.Hosts.ToListAsync());
        }

        // GET: Hosts/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Host host = await db.Hosts.FindAsync(id);
            if (host == null)
            {
                return HttpNotFound();
            }
            return View(host);
        }

        // GET: Hosts/Create
        public ActionResult Create()
        {
            ViewBag.DefaultNetwork = new SelectList(db.Networks, "Id", "Name");
            ViewBag.LocationId = new SelectList(db.Locations, "Id", "Name");
            ViewBag.HostTypeId = new SelectList(db.HostTypes, "Id", "Name");
            ViewBag.PhysicalHostId = new SelectList(db.Hosts.Where(e => e.IsPhysical == true), "Id", "Name");

            return View();
        }

        // POST: Hosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Description,DomainName,IpAddress,DefaultNetwork,DefaultNetworkIpAddress,HostTypeId,Make,LocationId,IsPhysical,PhyisicalHostId")] Host host)
        {
            ViewBag.DefaultNetwork = new SelectList(db.Networks, "Id", "Name", host.DefaultNetwork);
            ViewBag.LocationId = new SelectList(db.Locations, "Id", "Name", host.LocationId);
            ViewBag.HostTypeId = new SelectList(db.HostTypes, "Id", "Name", host.HostTypeId);
            ViewBag.PhysicalHostId = new SelectList(db.Hosts.Where(e => e.IsPhysical == true), "Id", "Name", host.PhysicalHostId);

            if (ModelState.IsValid)
            {
                if (string.IsNullOrEmpty(host.DefaultNetworkIpAddress))
                {
                    ModelState.AddModelError("", "Please specify the IP address of the host in the default network.");
                    return View(host);
                }
                var testHost = db.Locations.FirstOrDefault(e => e.Name == host.Name);
                if (testHost == null)
                {
                    var testHost2 = db.Locations.FirstOrDefault(e => e.Name == host.DomainName);
                    if (testHost2 == null)
                    {
                        db.Hosts.Add(host);
                        //Check if IP address belongs to this subnet
                        var network = await db.Networks.FindAsync(host.DefaultNetwork);
                        try
                        {
                            if (BusinessLogic.BusinessLogic.IsIpAddressInNetwork(network, host.DefaultNetworkIpAddress))
                            {
                                //Check if IP address is free
                                var testAssignment = db.HostAssignments.FirstOrDefault(e => e.NetworkId == network.Id && e.IpAddress == host.DefaultNetworkIpAddress);
                                if (testAssignment == null)
                                {
                                    var hostAssignment = new HostAssignment();
                                    hostAssignment.HostId = host.Id;
                                    hostAssignment.NetworkId = host.DefaultNetwork;
                                    hostAssignment.IpAddress = host.DefaultNetworkIpAddress;
                                    hostAssignment.DateAssigned = DateTime.Now.GetCondensedDateTime();
                                    db.HostAssignments.Add(hostAssignment);
                                    await db.SaveChangesAsync();
                                    return RedirectToAction("Index");
                                }
                                ModelState.AddModelError("", "The IP address you entered has already been assigned to another host.");
                                return View(host);
                            }
                            ModelState.AddModelError("", "The IP address you entered does not belong to the network you selected.");
                            return View(host);
                        }
                        catch (Exception e)
                        {
                            ModelState.AddModelError("", e.Message);
                            return View(host);
                        }
                    }
                    ModelState.AddModelError("", "A host with the same domain name already exists.");
                    return View(host);
                }
                ModelState.AddModelError("", "A host with the same name already exists.");
                return View(host);
            }
            return View(host);
        }

        // GET: Hosts/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Host host = await db.Hosts.FindAsync(id);
            if (host == null)
            {
                return HttpNotFound();
            }
            var hostNetworks = new List<int>();
            db.HostAssignments.Where(e => e.HostId == id).ToList().ForEach(e => hostNetworks.Add(e.NetworkId));
            ViewBag.DefaultNetwork = new SelectList(db.Networks.Where(e => hostNetworks.Contains(e.Id)), "Id", "Name", host.DefaultNetwork);
            ViewBag.LocationId = new SelectList(db.Locations, "Id", "Name", host.LocationId);
            ViewBag.HostTypeId = new SelectList(db.HostTypes, "Id", "Name", host.HostTypeId);
            ViewBag.PhysicalHostId = new SelectList(db.Hosts.Where(e => e.IsPhysical == true), "Id", "Name", host.PhysicalHostId);

            return View(host);
        }

        // POST: Hosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Description,DomainName,IpAddress,DefaultNetwork,DefaultNetworkIpAddress,HostTypeId,Make,LocationId,IsPhysical,PhysicalHostId")] Host host)
        {
            var hostNetworks = new List<int>();
            db.HostAssignments.Where(e => e.HostId == host.Id).ToList().ForEach(e => hostNetworks.Add(e.NetworkId));
            ViewBag.DefaultNetwork = new SelectList(db.Networks.Where(e => hostNetworks.Contains(e.Id)), "Id", "Name", host.DefaultNetwork);
            ViewBag.LocationId = new SelectList(db.Locations, "Id", "Name", host.LocationId);
            ViewBag.HostTypeId = new SelectList(db.HostTypes, "Id", "Name", host.HostTypeId);
            ViewBag.PhysicalHostId = new SelectList(db.Hosts.Where(e => e.IsPhysical == true), "Id", "Name", host.PhysicalHostId);

            if (ModelState.IsValid)
            {
                var testHost = db.Locations.FirstOrDefault(e => e.Name == host.Name && e.Id != host.Id);
                if (testHost == null)
                {
                    var testHost2 = db.Locations.FirstOrDefault(e => e.Name == host.DomainName && e.Id != host.Id);
                    if (testHost2 == null)
                    {
                        var hostAssignment = db.HostAssignments.Find(host.DefaultNetwork, host.Id, host.DefaultNetworkIpAddress);
                        host.DefaultNetworkIpAddress = hostAssignment.IpAddress;
                        db.Entry(host).State = EntityState.Modified;
                        await db.SaveChangesAsync();
                        return RedirectToAction("Details", new { id = host.Id });
                    }
                    ModelState.AddModelError("", "A host with the same domain name already exists.");
                }
                ModelState.AddModelError("", "A host with the same name already exists.");
            }
            return View(host);
        }

        // GET: Hosts/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Host host = await db.Hosts.FindAsync(id);
            if (host == null)
            {
                return HttpNotFound();
            }
            return View(host);
        }

        // POST: Hosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Host host = await db.Hosts.FindAsync(id);
            var applicationHostAssignments = db.ApplicationAssignments.Where(e => e.HostId == host.Id).ToList();
            if (applicationHostAssignments.Count() > 0)
            {
                ModelState.AddModelError("", $"This operation cannot be completed because the host has {applicationHostAssignments.Count()} application/s associated with it.");
                return View(host);
            }
            var applicationsWithAsDefault = db.Applications.Where(e => e.PrimaryHost == host.Id).ToList();
            if (applicationsWithAsDefault.Count() > 0)
            {

NetworkHostTracker/Controllers/NetworksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model;

namespace NetworkHostTracker.Controllers
{
    public class NetworksController : Controller
    {
        private NetHostTrackerContext db = new NetHostTrackerContext();

        // GET: Networks
        public async Task<ActionResult> Index()
        {
            return View(await db.Networks.ToListAsync());
        }

        // GET: Networks/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Network network = await db.Networks.FindAsync(id);
            if (network == null)
            {
                return HttpNotFound();
            }
            return View(network);
        }

        // GET: Networks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Networks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Description,IpAddress,NetMask,DefaultGateway")] Network network)
        {
            if (ModelState.IsValid)
            {
                var testNetwork = db.Locations.FirstOrDefault(e => e.Name == network.Name && e.Id != network.Id);
                if (testNetwork == null)
                {
                    db.Networks.Add(network);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", "A network with the same name already exists.");
            }
            return View(network);
        }

        // GET: Networks/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Network network = await db.Networks.FindAsync(id);
            if (network == null)
            {
                return HttpNotFound();
            }
            return View(network);
        }

        // POST: Networks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Description,IpAddress,NetMask,DefaultGateway")] Network network)
        {
            if (ModelState.IsValid)
            {
                var testNetwork = db.Locations.FirstOrDefault(e => e.Name == network.Name);
                if (testNetwork == null)
                {
                    db.Entry(network).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    return RedirectToAction("Details", new { id = network.Id });
                }
                ModelState.AddModelError("", "A network with the same name already exists.");
                return View(network);
            }
            return View(network);
        }

        // GET: Networks/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Network network = await db.Networks.FindAsync(id);
            if (network == null)
            {
                return HttpNotFound();
            }
            return View(network);
        }

        // POST: Networks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Network network = await db.Networks.FindAsync(id);
            var networkHostAssignments = db.HostAssignments.Where(e => e.NetworkId == network.Id).ToList();
            if (networkHostAssignments.Count() > 0)
            {
                ModelState.AddModelError("", $"This operation cannot be completed because the network has {networkHostAssignments.Count()} host/s associated with it.");
                return View(network);
            }
            var hostsWithAsDefault = db.Hosts.Where(e => e.DefaultNetwork == network.Id).ToList();
            if (hostsWithAsDefault.Count() > 0)
            {
                ModelState.AddModelError("", $"This operation cannot be completed because the network is set as the default network for {hostsWithAsDefault.Count()} host/s.");
                return View(network);
            }
            db.Networks.Remove(network);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NetworkHostTracker/Views/Networks/Create.cshtml
@model Model.Network

@{
    ViewBag.Title = "Create New Network";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h5 class="text-secondary">@ViewBag.Title</h5>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IpAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IpAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IpAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NetMask, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NetMask, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NetMask, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DefaultGateway, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DefaultGateway, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DefaultGateway, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                <button class="btn btn-info">@Html.ActionLink("Cancel", "Index", null, new { style = "decoration: none", @class = "text-light" })</button>
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NetworkHostTracker/Views/Networks/Delete.cshtml
@model Model.Network

@{
    ViewBag.Title = "Delete Network";
}

<h4 class="text-secondary">Are you sure you want to delete @Model.Name network?</h4>
<br />
@Html.ValidationSummary(true, "", new { @class = "text-danger" })
<div>
    <table class="display table table-striped table-bordered shadow" style="width:100%" width="100%" cellspacing="0">
        <thead>
            <tr class="bg-info">
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IpAddress)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NetMask)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DefaultGateway)
                </th>
                @*<th></th>*@
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Html.ActionLink(Model.Name, "Details", "Networks", new { id = Model.Id }, null)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.Description)
                </td>
                <td>
                    @Html.ActionLink(Model.IpAddress, "Details", "Networks", new { id = Model.Id }, null)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.NetMask)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.DefaultGateway)
                </td>
            </tr>
        </tbody>
    </table>
    <br />
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
            <button class="btn btn-info">@Html.ActionLink("Cancel", "Details", new { id = Model.Id }, new { style = "decoration: none", @class = "text-light" })</button>
        </div>
    }
</div>

NetworkHostTracker/Views/Networks/Details.cshtml
@model Model.Network

@{
    ViewBag.Title = "Network Name";
    ViewBag.SubTitle = Model.Name;
}

<h5 class="text-secondary">@ViewBag.Title &raquo; @ViewBag.SubTitle</h5>
<div class="btn-group">
    <span class="btn btn-sm btn-outline-light">@Html.ActionLink(" ", "Index", null, new { @class = "text-info fa fa-arrow-left" }) </span>
    <span class="btn btn-sm btn-outline-light">@Html.ActionLink(" ", "Edit", new { id = Model.Id }, new { @class = "text-info fa fa-edit" })</span>
    <span class="btn btn-sm btn-outline-light">@Html.ActionLink(" ", "Delete", new { id = Model.Id }, new { @class = "text-info fa fa-trash" })</span>
</div>

<table class="table table-striped able-bordered table-responsive-md shadow">
    <tr class="bg-info">
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IpAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NetMask)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DefaultGateway)
        </th>
    </tr>
    <tr>
        <td>
            @if (string.IsNullOrEmpty(Model.Description))
            {
                <i>None</i>
            }
            else
            {
                @Html.DisplayFor(modelItem => Model.Description)
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.IpAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.NetMask)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.DefaultGateway)
        </td>
    </tr>
</table>

<br />

<div>
    <div class="card shadow">
        <div class="card-header bg-info"><h5>Hosts</h5></div>
        <div class="card-body">
            <table class="display table table-striped table-bordered table-responsive-md table-hover" style="width:100%" id="report" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            Host
                        </th>
                        <th>
                            Description
                        </th>
                        <th>
                            Host IP Address
                        </th>
                        <th>
                            Host Type
                        </th>
                        <th>
                            Location
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        var context = new Model.NetHostTrackerContext();
                        var assignments = context.HostAssignments.Where(e => e.NetworkId == Model.Id).ToList();
                        var netIds = new List<int>();
                        assignments.ForEach(e => netIds.Add(e.NetworkId));
                    }
                    @foreach (var item in assignments)
                    {
                        <tr>
                            <td>
                                @Html.ActionLink(item.Host.Name, "Details", "Hosts", new { id = item.HostId }, null)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Host.Description)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IpAddress)
                                @Html.ActionLink(" ", "Edit", "HostAssignments", new { hostId = item.HostId, networkId = item.NetworkId, ipAddress = item.IpAddress }, new { @class = "fa fa-edit" })
                            </td>
                            <td>
                                @Html.ActionLink(item.Host.HostType.Name, "Details", "HostTypes", new { id = item.Host.HostTypeId }, null)
                            </td>
                            <td>
                                @Html.ActionLink(item.Host.Location.Name, "Details", "Locations", new { id = item.Host.LocationId }, null)
                            </td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>
    </div>

</div>

NetworkHostTracker/Views/Networks/Edit.cshtml
@model Model.Network

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h5 class="text-secondary">Edit '@Model.Name' Network</h5>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <div class="col-md-2">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label " })
            </div><div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IpAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IpAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IpAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NetMask, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NetMask, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NetMask, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DefaultGateway, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DefaultGateway, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DefaultGateway, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
                <button class="btn btn-info">@Html.ActionLink("Cancel", "Details", new { id = Model.Id }, new { style = "decoration: none", @class = "text-light" })</button>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NetworkHostTracker/Views/Networks/Index.cshtml
@model IEnumerable<Model.Network>

@{
    ViewBag.Title = "Networks";
}

<div class="card shadow">
    <div class="card-header bg-info">
        <h5 class="text-light">@ViewBag.Title</h5>
    </div>
    <div class="card-body">
        <p>
            @Html.ActionLink("  ", "Create", null, new { @class = "fa fa-plus-square" })
        </p>
        <hr />
        <table class="display table table-striped table-bordered" style="width:100%" id="report" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.IpAddress)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.NetMask)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DefaultGateway)
                    </th>
                    @*<th></th>*@
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @Html.ActionLink(item.Name, "Details", "Networks", new { id = item.Id }, null)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.ActionLink(item.IpAddress, "Details", "Networks", new { id = item.Id }, null)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NetMask)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DefaultGateway)
                    </td>
                    @*<td>
                    @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @class = "fa fa-edit" }) |
                    @Html.ActionLink(" ", "Create", "HostAssignments", new { networkId = item.Id }, new { @class = "fa fa-flash" }) |
                    @Html.ActionLink(" ", "Details", new { id = item.Id }, new { @class = "fa fa-search-plus" }) |
                    @Html.ActionLink(" ", "Delete", new { id = item.Id }, new { @class = "fa fa-trash" })
                    </td>*@
                </tr>
                }
            </tbody>

        </table>
    </div>
</div>